//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `Streaming.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Streaming;

public class response implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String action;

    public String titre;

    public String artiste;

    public String imgUrl;

    public String ref;

    public String statusCode;

    public response()
    {
        this.action = "";
        this.titre = "";
        this.artiste = "";
        this.imgUrl = "";
        this.ref = "";
        this.statusCode = "";
    }

    public response(String action, String titre, String artiste, String imgUrl, String ref, String statusCode)
    {
        this.action = action;
        this.titre = titre;
        this.artiste = artiste;
        this.imgUrl = imgUrl;
        this.ref = ref;
        this.statusCode = statusCode;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        response r = null;
        if(rhs instanceof response)
        {
            r = (response)rhs;
        }

        if(r != null)
        {
            if(this.action != r.action)
            {
                if(this.action == null || r.action == null || !this.action.equals(r.action))
                {
                    return false;
                }
            }
            if(this.titre != r.titre)
            {
                if(this.titre == null || r.titre == null || !this.titre.equals(r.titre))
                {
                    return false;
                }
            }
            if(this.artiste != r.artiste)
            {
                if(this.artiste == null || r.artiste == null || !this.artiste.equals(r.artiste))
                {
                    return false;
                }
            }
            if(this.imgUrl != r.imgUrl)
            {
                if(this.imgUrl == null || r.imgUrl == null || !this.imgUrl.equals(r.imgUrl))
                {
                    return false;
                }
            }
            if(this.ref != r.ref)
            {
                if(this.ref == null || r.ref == null || !this.ref.equals(r.ref))
                {
                    return false;
                }
            }
            if(this.statusCode != r.statusCode)
            {
                if(this.statusCode == null || r.statusCode == null || !this.statusCode.equals(r.statusCode))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Streaming::response");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, action);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, titre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, artiste);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, imgUrl);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, ref);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, statusCode);
        return h_;
    }

    public response clone()
    {
        response c = null;
        try
        {
            c = (response)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.action);
        ostr.writeString(this.titre);
        ostr.writeString(this.artiste);
        ostr.writeString(this.imgUrl);
        ostr.writeString(this.ref);
        ostr.writeString(this.statusCode);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.action = istr.readString();
        this.titre = istr.readString();
        this.artiste = istr.readString();
        this.imgUrl = istr.readString();
        this.ref = istr.readString();
        this.statusCode = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, response v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public response ice_read(com.zeroc.Ice.InputStream istr)
    {
        response v = new response();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<response> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, response v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<response> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(response.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final response _nullMarshalValue = new response();

    /** @hidden */
    public static final long serialVersionUID = 2056390056818007640L;
}
